### ISSUE TITLE
wich variables i need to chante for 192.168.88.186 to datosabiertos.felipeurrego.com

### ISSUE THREAD

**Issue by johnfelipe** [vrk-kpa/opendata#1540]
i have a VMware appliance with ubuntu 20, and now is all set
my Windows host that virtual appliance in my hosts file in windows i put `192.168.88.186 datosabiertos.felipeurrego.com` 

in `/root/opendata/docker/.env`

i change this:

```
#DOMAIN_NAME=localhost
DOMAIN_NAME=datosabiertos.felipeurrego.com
SECONDARY_DOMAIN_NAME="nginx"
BASE_DOMAIN_NAME="localhost.not-exists"
SECONDARY_BASE_DOMAIN_NAME="nginx.not-exists"
#NAMESERVER=127.0.0.11
NAMESERVER=127.0.0.1
```

when put `docker-compose up --build`

show all UP

```
docker_ckan_cron_1  ... done
docker_nginx_1      ... done
docker_drupal_1     ... done
docker_ckan_1       ... done
docker_solr_1       ... done
docker_datapusher_1 ... done
docker_redis_1      ... done
docker_postgres_1   ... done
docker_mailhog_1    ... done

```

But in chrome in my windows

![SNAG-1304](https://user-images.githubusercontent.com/428820/174420938-718bf6c3-d136-4168-a391-c98ef6402491.png)

**Comment by Zharktas** [comment]
It takes a while the containers to install everything after they have started, but we have no resources to provide support.

**Comment by johnfelipe** [comment]
need to edit all localhost to my ip?

**Comment by johnfelipe** [comment]
@Zharktas pls help me for deploy into a server with 0.0.0.0 not localhost or 127.0.0.1
