### ISSUE TITLE
"Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again."

### ISSUE THREAD

**Issue by johnfelipe** [vrk-kpa/opendata#1550]
Here is log an steps

https://gist.github.com/johnfelipe/31d901a3a76c26a86403694f29ca7228

Dear i want contribute with spanish, french and italian
this repo is most complete i see in data portal enviroments
Pls guide me
Pls give me hand pls

**Comment by Zharktas** [comment]
Ansible has not been used in months and has been now deleted.
