### ISSUE TITLE
workflow in vagrant

### ISSUE THREAD

**Issue by johnfelipe** [vrk-kpa/opendata#1551]
```
git clone https://github.com/vrk-kpa/opendata.git

cd opendata

git submodule update --init --recursive

```

im edit this

`    ytp.vm.network :private_network, ip: "172.19.42.144"`

next this

`vagrant up`

this is log

https://gist.github.com/ea398014b2693a20209a0ba30409da3b

now what?

**Comment by johnfelipe** [comment]
anyone, pls only guide me for this matter

**Comment by Zharktas** [comment]
Vagrant was not actually in use for months and has been now deleted.
