### ISSUE TITLE
CloudFormation ALB now supports redirect

### ISSUE THREAD

**Issue by gene1wood** [vrk-kpa/opendata#361]
#149 adds an ALB but at the time CloudFormation didn't support `redirect` (as shown in 
[these lines](https://github.com/vrk-kpa/opendata/commit/473bbf62927bc874500ef4719b78ec078c16e3fc#diff-50748072026684e0af8b7daf2d3c1374R324)). It does now. You may want to update your template to use the new feature.

**Comment by tvallas** [comment]
Thanks for pointing this out. Actually we are currently implementing Cloudfront CDN (https://github.com/vrk-kpa/opendata/blob/AV-247_cloudfront_distribution/cloudformation/cloudfront.yml) that will take care of http to https redirects in future. Once this is use we'll clean the ALB configs from http listener.
